/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// FieldSelectValidation
    /// </summary>
    [DataContract]
    public partial class FieldSelectValidation :  IEquatable<FieldSelectValidation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldSelectValidation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public FieldSelectValidation()
        {
        }
        
        /// <summary>
        /// Describes the valid options for this selectbox
        /// </summary>
        /// <value>Describes the valid options for this selectbox</value>
        [DataMember(Name="in", EmitDefaultValue=false)]
        public Object In { get; private set; }

        /// <summary>
        /// Describes whether the field is optional or not
        /// </summary>
        /// <value>Describes whether the field is optional or not</value>
        [DataMember(Name="allow_blank", EmitDefaultValue=false)]
        public bool? AllowBlank { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FieldSelectValidation {\n");
            sb.Append("  In: ").Append(In).Append("\n");
            sb.Append("  AllowBlank: ").Append(AllowBlank).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FieldSelectValidation);
        }

        /// <summary>
        /// Returns true if FieldSelectValidation instances are equal
        /// </summary>
        /// <param name="input">Instance of FieldSelectValidation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FieldSelectValidation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.In == input.In ||
                    (this.In != null &&
                    this.In.Equals(input.In))
                ) && 
                (
                    this.AllowBlank == input.AllowBlank ||
                    (this.AllowBlank != null &&
                    this.AllowBlank.Equals(input.AllowBlank))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.In != null)
                    hashCode = hashCode * 59 + this.In.GetHashCode();
                if (this.AllowBlank != null)
                    hashCode = hashCode * 59 + this.AllowBlank.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
