/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// PayinMethodRequest
    /// </summary>
    [DataContract]
    public partial class PayinMethodRequest :  IEquatable<PayinMethodRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayinMethodRequest" /> class.
        /// </summary>
        /// <param name="payinMethod">payinMethod.</param>
        public PayinMethodRequest(PayinMethod payinMethod = default(PayinMethod))
        {
            this.PayinMethod = payinMethod;
        }
        
        /// <summary>
        /// Gets or Sets PayinMethod
        /// </summary>
        [DataMember(Name="payin_method", EmitDefaultValue=false)]
        public PayinMethod PayinMethod { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PayinMethodRequest {\n");
            sb.Append("  PayinMethod: ").Append(PayinMethod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PayinMethodRequest);
        }

        /// <summary>
        /// Returns true if PayinMethodRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PayinMethodRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PayinMethodRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PayinMethod == input.PayinMethod ||
                    (this.PayinMethod != null &&
                    this.PayinMethod.Equals(input.PayinMethod))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PayinMethod != null)
                    hashCode = hashCode * 59 + this.PayinMethod.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
