/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// The type of the identity card used by the sender or recipient:  - &#x60;PP&#x60;: Passport - &#x60;NI&#x60;: National Identity Card - &#x60;O&#x60;: Other type of identity card
    /// </summary>
    /// <value>The type of the identity card used by the sender or recipient:  - &#x60;PP&#x60;: Passport - &#x60;NI&#x60;: National Identity Card - &#x60;O&#x60;: Other type of identity card</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PayoutMethodIdentityCardTypeEnum
    {
        /// <summary>
        /// Enum O for value: O
        /// </summary>
        [EnumMember(Value = "O")]
        O = 1,

        /// <summary>
        /// Enum PP for value: PP
        /// </summary>
        [EnumMember(Value = "PP")]
        PP = 2,

        /// <summary>
        /// Enum NI for value: NI
        /// </summary>
        [EnumMember(Value = "NI")]
        NI = 3

    }

}
