/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing Currency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CurrencyTests
    {
        // TODO uncomment below to declare an instance variable for Currency
        //private Currency instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Currency
            //instance = new Currency();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Currency
        /// </summary>
        [Test]
        public void CurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Currency
            //Assert.IsInstanceOfType<Currency> (instance, "variable 'instance' is a Currency");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Decimals'
        /// </summary>
        [Test]
        public void DecimalsTest()
        {
            // TODO unit test for the property 'Decimals'
        }
        /// <summary>
        /// Test the property 'SubunitToUnit'
        /// </summary>
        [Test]
        public void SubunitToUnitTest()
        {
            // TODO unit test for the property 'SubunitToUnit'
        }
        /// <summary>
        /// Test the property 'Primary'
        /// </summary>
        [Test]
        public void PrimaryTest()
        {
            // TODO unit test for the property 'Primary'
        }
        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Test]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }
        /// <summary>
        /// Test the property 'Margin'
        /// </summary>
        [Test]
        public void MarginTest()
        {
            // TODO unit test for the property 'Margin'
        }
        /// <summary>
        /// Test the property 'UsdEquivalent'
        /// </summary>
        [Test]
        public void UsdEquivalentTest()
        {
            // TODO unit test for the property 'UsdEquivalent'
        }

    }

}
