/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayinMethodDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayinMethodDetailsTests
    {
        // TODO uncomment below to declare an instance variable for PayinMethodDetails
        //private PayinMethodDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayinMethodDetails
            //instance = new PayinMethodDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayinMethodDetails
        /// </summary>
        [Test]
        public void PayinMethodDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayinMethodDetails
            //Assert.IsInstanceOfType<PayinMethodDetails> (instance, "variable 'instance' is a PayinMethodDetails");
        }


        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Test]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'SendInstructions'
        /// </summary>
        [Test]
        public void SendInstructionsTest()
        {
            // TODO unit test for the property 'SendInstructions'
        }

    }

}
