/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PaymentMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentMethodTests
    {
        // TODO uncomment below to declare an instance variable for PaymentMethod
        //private PaymentMethod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentMethod
            //instance = new PaymentMethod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentMethod
        /// </summary>
        [Test]
        public void PaymentMethodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentMethod
            //Assert.IsInstanceOfType<PaymentMethod> (instance, "variable 'instance' is a PaymentMethod");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'OtcPermitted'
        /// </summary>
        [Test]
        public void OtcPermittedTest()
        {
            // TODO unit test for the property 'OtcPermitted'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Test]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

    }

}
