/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayoutMethodGenderEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayoutMethodGenderEnumTests
    {
        // TODO uncomment below to declare an instance variable for PayoutMethodGenderEnum
        //private PayoutMethodGenderEnum instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayoutMethodGenderEnum
            //instance = new PayoutMethodGenderEnum();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayoutMethodGenderEnum
        /// </summary>
        [Test]
        public void PayoutMethodGenderEnumInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayoutMethodGenderEnum
            //Assert.IsInstanceOfType<PayoutMethodGenderEnum> (instance, "variable 'instance' is a PayoutMethodGenderEnum");
        }



    }

}
