/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayoutMethodIdentityCardTypeEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayoutMethodIdentityCardTypeEnumTests
    {
        // TODO uncomment below to declare an instance variable for PayoutMethodIdentityCardTypeEnum
        //private PayoutMethodIdentityCardTypeEnum instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayoutMethodIdentityCardTypeEnum
            //instance = new PayoutMethodIdentityCardTypeEnum();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayoutMethodIdentityCardTypeEnum
        /// </summary>
        [Test]
        public void PayoutMethodIdentityCardTypeEnumInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayoutMethodIdentityCardTypeEnum
            //Assert.IsInstanceOfType<PayoutMethodIdentityCardTypeEnum> (instance, "variable 'instance' is a PayoutMethodIdentityCardTypeEnum");
        }



    }

}
