/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayoutMethodDetailsMADCash
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayoutMethodDetailsMADCashTests
    {
        // TODO uncomment below to declare an instance variable for PayoutMethodDetailsMADCash
        //private PayoutMethodDetailsMADCash instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayoutMethodDetailsMADCash
            //instance = new PayoutMethodDetailsMADCash();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayoutMethodDetailsMADCash
        /// </summary>
        [Test]
        public void PayoutMethodDetailsMADCashInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayoutMethodDetailsMADCash
            //Assert.IsInstanceOfType<PayoutMethodDetailsMADCash> (instance, "variable 'instance' is a PayoutMethodDetailsMADCash");
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'SenderIdentityCardType'
        /// </summary>
        [Test]
        public void SenderIdentityCardTypeTest()
        {
            // TODO unit test for the property 'SenderIdentityCardType'
        }
        /// <summary>
        /// Test the property 'SenderIdentityCardId'
        /// </summary>
        [Test]
        public void SenderIdentityCardIdTest()
        {
            // TODO unit test for the property 'SenderIdentityCardId'
        }
        /// <summary>
        /// Test the property 'SenderCityOfBirth'
        /// </summary>
        [Test]
        public void SenderCityOfBirthTest()
        {
            // TODO unit test for the property 'SenderCityOfBirth'
        }
        /// <summary>
        /// Test the property 'SenderCountryOfBirth'
        /// </summary>
        [Test]
        public void SenderCountryOfBirthTest()
        {
            // TODO unit test for the property 'SenderCountryOfBirth'
        }
        /// <summary>
        /// Test the property 'SenderGender'
        /// </summary>
        [Test]
        public void SenderGenderTest()
        {
            // TODO unit test for the property 'SenderGender'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'IdentityCardType'
        /// </summary>
        [Test]
        public void IdentityCardTypeTest()
        {
            // TODO unit test for the property 'IdentityCardType'
        }
        /// <summary>
        /// Test the property 'IdentityCardId'
        /// </summary>
        [Test]
        public void IdentityCardIdTest()
        {
            // TODO unit test for the property 'IdentityCardId'
        }

    }

}
