/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing RecipientWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecipientWebhookTests
    {
        // TODO uncomment below to declare an instance variable for RecipientWebhook
        //private RecipientWebhook instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecipientWebhook
            //instance = new RecipientWebhook();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecipientWebhook
        /// </summary>
        [Test]
        public void RecipientWebhookInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecipientWebhook
            //Assert.IsInstanceOfType<RecipientWebhook> (instance, "variable 'instance' is a RecipientWebhook");
        }


        /// <summary>
        /// Test the property 'Webhook'
        /// </summary>
        [Test]
        public void WebhookTest()
        {
            // TODO unit test for the property 'Webhook'
        }
        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Test]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

    }

}
