/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing WebhookLogListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookLogListResponseTests
    {
        // TODO uncomment below to declare an instance variable for WebhookLogListResponse
        //private WebhookLogListResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookLogListResponse
            //instance = new WebhookLogListResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookLogListResponse
        /// </summary>
        [Test]
        public void WebhookLogListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookLogListResponse
            //Assert.IsInstanceOfType<WebhookLogListResponse> (instance, "variable 'instance' is a WebhookLogListResponse");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Test]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

    }

}
