/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing WebhookLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookLogTests
    {
        // TODO uncomment below to declare an instance variable for WebhookLog
        //private WebhookLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookLog
            //instance = new WebhookLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookLog
        /// </summary>
        [Test]
        public void WebhookLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookLog
            //Assert.IsInstanceOfType<WebhookLog> (instance, "variable 'instance' is a WebhookLog");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Test]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'ParentType'
        /// </summary>
        [Test]
        public void ParentTypeTest()
        {
            // TODO unit test for the property 'ParentType'
        }

    }

}
