/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using TransferZero.Sdk.Client;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing AccountDebitsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AccountDebitsApiTests
    {
        private AccountDebitsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccountDebitsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountDebitsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AccountDebitsApi
            //Assert.IsInstanceOfType(typeof(AccountDebitsApi), instance, "instance is a AccountDebitsApi");
        }

        
        /// <summary>
        /// Test GetAccountsDebit
        /// </summary>
        [Test]
        public void GetAccountsDebitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? accountDebitID = null;
            //var response = instance.GetAccountsDebit(accountDebitID);
            //Assert.IsInstanceOf<DebitResponse> (response, "response is DebitResponse");
        }
        
        /// <summary>
        /// Test GetAccountsDebits
        /// </summary>
        [Test]
        public void GetAccountsDebitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? per = null;
            //var response = instance.GetAccountsDebits(page, per);
            //Assert.IsInstanceOf<DebitListResponse> (response, "response is DebitListResponse");
        }
        
        /// <summary>
        /// Test PostAccountsDebits
        /// </summary>
        [Test]
        public void PostAccountsDebitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DebitRequestWrapper debitRequestWrapper = null;
            //var response = instance.PostAccountsDebits(debitRequestWrapper);
            //Assert.IsInstanceOf<DebitListResponse> (response, "response is DebitListResponse");
        }
        
    }

}
