/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using TransferZero.Sdk.Client;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing APILogsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class APILogsApiTests
    {
        private APILogsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new APILogsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of APILogsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' APILogsApi
            //Assert.IsInstanceOfType(typeof(APILogsApi), instance, "instance is a APILogsApi");
        }

        
        /// <summary>
        /// Test GetApiLog
        /// </summary>
        [Test]
        public void GetApiLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? aPILogID = null;
            //var response = instance.GetApiLog(aPILogID);
            //Assert.IsInstanceOf<ApiLogResponse> (response, "response is ApiLogResponse");
        }
        
        /// <summary>
        /// Test GetApiLogs
        /// </summary>
        [Test]
        public void GetApiLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? per = null;
            //string createdAtFrom = null;
            //string createdAtTo = null;
            //var response = instance.GetApiLogs(page, per, createdAtFrom, createdAtTo);
            //Assert.IsInstanceOf<ApiLogListResponse> (response, "response is ApiLogListResponse");
        }
        
    }

}
