/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using TransferZero.Sdk.Client;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing CurrencyInfoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CurrencyInfoApiTests
    {
        private CurrencyInfoApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CurrencyInfoApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CurrencyInfoApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CurrencyInfoApi
            //Assert.IsInstanceOfType(typeof(CurrencyInfoApi), instance, "instance is a CurrencyInfoApi");
        }

        
        /// <summary>
        /// Test InfoCurrencies
        /// </summary>
        [Test]
        public void InfoCurrenciesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InfoCurrencies();
            //Assert.IsInstanceOf<CurrencyListResponse> (response, "response is CurrencyListResponse");
        }
        
        /// <summary>
        /// Test InfoCurrenciesIn
        /// </summary>
        [Test]
        public void InfoCurrenciesInTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InfoCurrenciesIn();
            //Assert.IsInstanceOf<CurrencyExchangeListResponse> (response, "response is CurrencyExchangeListResponse");
        }
        
        /// <summary>
        /// Test InfoCurrenciesOut
        /// </summary>
        [Test]
        public void InfoCurrenciesOutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InfoCurrenciesOut();
            //Assert.IsInstanceOf<CurrencyExchangeListResponse> (response, "response is CurrencyExchangeListResponse");
        }
        
    }

}
